CREATE TABLE "GCG_4253_PMWO_BI"(
 "Project" CHAR(7),
 "Part" CHAR(20),
 "Loc" CHAR(2),
 "Descr" VARCHAR(30),
 "ShipToLoc" CHAR(2),
 "ShipDate" DATE,
 "Shipping_Rep" VARCHAR(10),
 "CustomerPO" VARCHAR(20),
 "Mark_Shipment" VARCHAR(20),
 "Shipped_Via" CHAR(20),
 "Cartons" DOUBLE,
 "Weight" DOUBLE,
 "Waybill_Number" VARCHAR(20),
 "RUNID" BIGINT,
 "Qty_Ship" INTEGER,
 "Pklst_No" VARCHAR(20),
 "Comments" VARCHAR(500));
